/*
 *  ======== user_rf_switch_cfg.c ========
 *
 *  Commented stub for the BDE-MB1352P71 RF switch configuration.
 *
 *  Why this file exists:
 *  - The BDE module uses a different Sub-1 GHz RF switch truth table than the
 *    TI LP_CC1352P7_1 LaunchPad examples.
 *  - The BDE module routes DIO29/DIO30 internally to the RF switch.
 *  - RF switch behavior must be controlled by the RF driver callback, not by
 *    ordinary application GPIO toggling.
 *
 *  BDE truth table:
 *      Off : DIO29 = 0, DIO30 = 0
 *      TX  : DIO29 = 1, DIO30 = 0
 *      RX  : DIO29 = 0, DIO30 = 1
 *
 *  Important:
 *  - This project template does not currently instantiate the RF driver, so
 *    this file is intentionally a stub and is not compiled by the makefiles.
 *  - Before enabling this file, add and configure the RF driver in SysConfig.
 *  - SysConfig must generate the RF antenna pin macros used below, typically:
 *      CONFIG_RF_ANTENNA_PIN_SUB_1_G
 *      CONFIG_RF_ANTENNA_PIN_HIGH_PA
 *  - Those RF pins should map to the BDE module's internal switch control
 *    lines on DIO29 and DIO30.
 *
 *  Integration steps when RF is added later:
 *  1. Add /ti/drivers/RF to the .syscfg.
 *  2. Configure the RF antenna multiplexer pins for the BDE module.
 *  3. Add this file to the active build.
 *  4. Register this callback wherever the chosen stack/example expects the RF
 *     antenna-switch callback to be supplied.
 *
 *  The implementation below is wrapped in #if 0 so the file can live in the
 *  repo as documentation without breaking builds before RF support is enabled.
 */

#if 0

#include <stddef.h>
#include <stdint.h>

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/ioc.h)

#include "ti_drivers_config.h"
#include <ti/drivers/GPIO.h>
#include <ti/drivers/rf/RF.h>

/*
 *  ======== rfDriverCallbackAntennaSwitching ========
 *  Configure the BDE module RF switch for the active RF path.
 *
 *  Notes:
 *  - CONFIG_RF_ANTENNA_PIN_SUB_1_G and CONFIG_RF_ANTENNA_PIN_HIGH_PA are
 *    generated by SysConfig once the RF driver is configured.
 *  - For the BDE module, these two logical antenna pins should be mapped onto
 *    the module's internal RF switch control pins DIO29 and DIO30.
 */
void rfDriverCallbackAntennaSwitching(RF_Handle client,
                                      RF_GlobalEvent events,
                                      void *arg)
{
    if (events & RF_GlobalEventRadioSetup) {
        bool sub1GHz = false;
        uint8_t loDivider = 0;

        /* Put both RF switch control pins in the "off" state first. */
        GPIO_write(CONFIG_RF_ANTENNA_PIN_SUB_1_G, 0);
        GPIO_write(CONFIG_RF_ANTENNA_PIN_HIGH_PA, 0);

        /* Determine whether the current setup is using the Sub-1 GHz front end. */
        RF_TxPowerTable_PAType paType =
            (RF_TxPowerTable_PAType)RF_getTxPower(client).paType;
        RF_RadioSetup *setupCommand = (RF_RadioSetup *)arg;

        switch (setupCommand->common.commandNo) {
            case CMD_RADIO_SETUP:
            case CMD_BLE5_RADIO_SETUP:
                loDivider = RF_LODIVIDER_MASK & setupCommand->common.loDivider;
                if (loDivider != 0) {
                    sub1GHz = true;
                }
                break;

            case CMD_PROP_RADIO_DIV_SETUP:
                loDivider = RF_LODIVIDER_MASK & setupCommand->prop_div.loDivider;
                if (loDivider != 0) {
                    sub1GHz = true;
                }
                break;

            default:
                break;
        }

        if (sub1GHz) {
            if (paType == RF_TxPowerTable_HighPA) {
                /*
                 * High-power TX path:
                 *   DIO29 = 1
                 *   DIO30 = 0
                 *
                 * RFC_GPO3 is used as the PA-enable work-around used in TI
                 * examples for CC1352P-class devices.
                 */
                GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_SUB_1_G,
                                     GPIO_CFG_OUTPUT,
                                     IOC_PORT_RFC_GPO0);
                GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_HIGH_PA,
                                     GPIO_CFG_OUTPUT,
                                     IOC_PORT_RFC_GPO3);
            }
            else {
                /*
                 * Sub-1 GHz receive / non-HighPA path:
                 *   DIO29 = 0
                 *   DIO30 = 1
                 */
                GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_HIGH_PA,
                                     GPIO_CFG_OUTPUT,
                                     IOC_PORT_GPIO);
                GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_SUB_1_G,
                                     GPIO_CFG_OUTPUT | GPIO_CFG_OUT_HIGH,
                                     IOC_PORT_GPIO);
            }
        }
    }
    else if (events & RF_GlobalEventRadioPowerDown) {
        /* Restore both RF switch control pins to the "off" state. */
        GPIO_write(CONFIG_RF_ANTENNA_PIN_SUB_1_G, 0);
        GPIO_write(CONFIG_RF_ANTENNA_PIN_HIGH_PA, 0);

        /* Return the mux settings to plain GPIO when the radio powers down. */
        GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_SUB_1_G,
                             GPIO_CFG_OUTPUT,
                             IOC_PORT_GPIO);
        GPIO_setConfigAndMux(CONFIG_RF_ANTENNA_PIN_HIGH_PA,
                             GPIO_CFG_OUTPUT,
                             IOC_PORT_GPIO);
    }
}

#endif
