// This file is autogenerated by Simplicity Configuration Tools.
// The contents of this file will be replaced in their entirety upon regeneration.
// 
// Source template file: sl_wisun_keychain_builtin.c.jinja


#include <stdint.h>
#include <stdlib.h>
#include "sl_wisun_keychain.h"
#include "sl_wisun_silabs_certificates.h"

const uint32_t sl_wisun_keychain_builtin_trustedca_count = 1;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_trustedca[] = {
  { SILABS_ROOT_CERT, sizeof(SILABS_ROOT_CERT), SL_WISUN_KEYCHAIN_BUILTIN },
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};

const uint32_t sl_wisun_keychain_builtin_devicecert_count = 1;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_devicecert[] = {
  { SILABS_DEVICE_CERT, sizeof(SILABS_DEVICE_CERT), SL_WISUN_KEYCHAIN_BUILTIN },
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};

const uint32_t sl_wisun_keychain_builtin_devicekey_count = 1;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_devicekey[] = {
  { SILABS_DEVICE_KEY, sizeof(SILABS_DEVICE_KEY), SL_WISUN_KEYCHAIN_BUILTIN },
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};
